In [1]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv("Data\\mlb_elo.csv")
df

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,...,pitcher1_rgs,pitcher2_rgs,pitcher1_adj,pitcher2_adj,rating_prob1,rating_prob2,rating1_post,rating2_post,score1,score2
0,2020-10-09,2020,1,d,LAD,SDP,1598.290926,1525.832831,0.635558,0.364442,...,NaN,NaN,NaN,NaN,0.635030,0.364970,NaN,NaN,NaN,NaN
1,2020-10-09,2020,1,d,ATL,FLA,1543.508397,1482.006574,0.615867,0.384133,...,NaN,NaN,NaN,NaN,0.629976,0.370024,NaN,NaN,NaN,NaN
2,2020-10-08,2020,1,d,TBD,NYY,1566.075394,1557.931446,0.515622,0.484378,...,NaN,NaN,NaN,NaN,0.507634,0.492366,NaN,NaN,NaN,NaN
3,2020-10-08,2020,1,d,SDP,LAD,1525.832831,1598.290926,0.364442,0.635558,...,NaN,NaN,NaN,NaN,0.364970,0.635030,NaN,NaN,NaN,NaN
4,2020-10-08,2020,1,d,OAK,HOU,1547.618027,1542.711978,0.509413,0.490587,...,NaN,NaN,NaN,NaN,0.482885,0.517115,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220941,1871-05-09,1871,0,NaN,TRO,ATL,1450.000000,1451.483000,0.532359,0.467641,...,NaN,NaN,NaN,NaN,0.522460,0.477540,1448.525,1452.958,5.0,9.0
220942,1871-05-08,1871,0,NaN,CHC,CL1,1450.000000,1451.943000,0.531700,0.468300,...,NaN,NaN,NaN,NaN,0.528402,0.471598,1451.256,1450.687,14.0,12.0
220943,1871-05-06,1871,0,NaN,RC1,CL1,1450.000000,1448.754000,0.536268,0.463732,...,NaN,NaN,NaN,NaN,0.532974,0.467026,1446.810,1451.943,4.0,12.0
220944,1871-05-05,1871,0,NaN,WS3,ATL,1450.000000,1450.000000,0.534484,0.465516,...,NaN,NaN,NaN,NaN,0.534484,0.465516,1448.517,1451.483,18.0,20.0
220945,1871-05-04,1871,0,NaN,FW1,CL1,1450.000000,1450.000000,0.534484,0.465516,...,NaN,NaN,NaN,NaN,0.534484,0.465516,1451.246,1448.754,2.0,0.0

In [13]:
df1 = pd.read_csv("Data\\mlb_elo_latest.csv")
df1

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,...,pitcher1_rgs,pitcher2_rgs,pitcher1_adj,pitcher2_adj,rating_prob1,rating_prob2,rating1_post,rating2_post,score1,score2
0,2020-10-09,2020,1,d,LAD,SDP,1598.290926,1525.832831,0.635558,0.364442,...,NaN,NaN,NaN,NaN,0.635030,0.364970,NaN,NaN,NaN,NaN
1,2020-10-09,2020,1,d,ATL,FLA,1543.508397,1482.006574,0.615867,0.384133,...,NaN,NaN,NaN,NaN,0.629976,0.370024,NaN,NaN,NaN,NaN
2,2020-10-08,2020,1,d,TBD,NYY,1566.075394,1557.931446,0.515622,0.484378,...,NaN,NaN,NaN,NaN,0.507634,0.492366,NaN,NaN,NaN,NaN
3,2020-10-08,2020,1,d,SDP,LAD,1525.832831,1598.290926,0.364442,0.635558,...,NaN,NaN,NaN,NaN,0.364970,0.635030,NaN,NaN,NaN,NaN
4,2020-10-08,2020,1,d,OAK,HOU,1547.618027,1542.711978,0.509413,0.490587,...,NaN,NaN,NaN,NaN,0.482885,0.517115,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,2020-07-24,2020,0,NaN,TBD,TOR,1537.750707,1487.408999,0.605383,0.394617,...,59.143800,56.199388,21.387997,22.869271,0.602440,0.397560,1537.654179,1480.303579,4.0,6.0
932,2020-07-24,2020,0,NaN,CIN,DET,1490.427814,1420.458239,0.632029,0.367971,...,58.879686,49.587500,25.182845,2.579873,0.665662,0.334338,1523.137206,1434.768526,7.0,1.0
933,2020-07-24,2020,0,NaN,NYM,ATL,1521.484830,1528.909097,0.523836,0.476164,...,64.418447,55.793568,53.729606,22.737531,0.563735,0.436265,1530.004769,1527.126229,1.0,0.0
934,2020-07-23,2020,0,NaN,LAD,SFG,1561.949414,1487.819917,0.637581,0.362419,...,48.700313,49.333010,-16.907113,1.884300,0.670766,0.329234,1585.954334,1452.175432,8.0,1.0
935,2020-07-23,2020,0,NaN,WSN,NYY,1561.015923,1558.092336,0.538669,0.461331,...,60.930717,67.188358,19.423532,51.214276,0.438047,0.561953,1546.677919,1572.468667,1.0,4.0